---
title: "Project 11"
description: |
  A short description of the post.
author:
  - name: Sajib Devnath
    url: https://www.sajibdevnath.com
date: 12-21-2020
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev = "png", dev.args = list(type = "cairo-png"))
options(repr.plot.width = 5, repr.plot.height = 4)
```


```{r}
library(tidyverse)
library(lubridate)
library(patchwork)
theme_set(theme_minimal())
```


```{r}
bottom <- read_csv(here::here("data", "bottom_line.csv"),
                   col_types = cols(Ping_date = col_datetime(format = "%m/%d/%Y"))) %>% 
  rename_all(tolower)

glimpse(bottom)
```

```{r}
bottom_clean <- bottom %>% 
  filter(position_status == 1) %>% 
  select(ping_date, ping_time, latitude, longitude, depth) %>% 
  mutate(date_time = ymd_hms(paste(ping_date, ping_time))) %>% 
  ## calculate the distance between latitude and longitude along rows of columns
  mutate(
     distance_between = c(
       0, geosphere::distHaversine(cbind(longitude[-n()], latitude[-n()]),
                                                     cbind(longitude[ -1], latitude[ -1]))),                         
       distance_along = cumsum(distance_between)
  )
  
glimpse(bottom_clean)
```


```{r}
p_ship_track <- ggplot(bottom_clean, aes(longitude, latitude)) +
  geom_point(size = .5) +
  labs(x = "Longitude", y = "Latitude")

p_bathymetry <- ggplot(bottom_clean, aes(distance_along, depth)) +
  geom_point(size = .5) +
  labs(x = "Distance along trackline (m)", y = "Depth (m)") +
  scale_y_reverse()

p_ship_track + p_bathymetry
```


```{r}
acoustic <- read_csv(here::here("data", "acoustic.csv"), 
                     col_types = cols(Date_M = col_datetime(format = "%Y%m%d")))  %>% 
  filter(Lon_M != 999.0)

glimpse(acoustic)
```

```{r}
variables_keep <- c("Interval", "Layer", "Sv_mean", "Frequency", 
               "Date_M", "Time_S", "Time_E", "Lat_M", "Lon_M")

Sv_layer1 <- acoustic %>%
    select(variables_keep) %>% 
    rename(Spatial_interval = Interval, Date = Date_M) %>%
    filter(Layer == "1")  %>% 
    mutate(Datetime_start = Date + Time_S,
           Datetime_end = Date + Time_E)  %>% 
    arrange(Datetime_start) 

glimpse(Sv_layer1)
```


```{r}
Sv <- Sv_layer1 %>% 
  mutate(Distance_between = c(0, geosphere::distHaversine(cbind(Lon_M[-n()], Lat_M[-n()]),       
                                               cbind(Lon_M[  -1], Lat_M[  -1]))),
       Distance_along = cumsum(Distance_between)) %>%
  na_if(-999.0) %>% 
  mutate(Time_interval = interval(Datetime_start, Datetime_end))

glimpse(Sv)
```


```{r}
# Name the function
get_Interval_by_time <- function(bottom_data){
  res <- Sv$Spatial_interval[bottom_data %within% Sv$Time_interval]
  if(length(res)==0) return(NA)         # dealing with NAs
  return(res)
}
 
# Map the track line interval value to the bottom_clean data
bottom_spatial_interval_segments <- bottom_clean  %>% 
    mutate(trackline_interval = purrr::map_dbl(date_time, get_Interval_by_time))

# Inspect the first 15 rows
head(bottom_spatial_interval_segments, 15)
```



```{r}
# Group bottom_clean and calculate the mean depth
bottom_intervals <- bottom_spatial_interval_segments %>%
    group_by(trackline_interval) %>%
    summarize(depth_mean = mean(depth)) %>%
    ungroup()

# Join the bottom intervals data to the acoustic data
Sv_and_depth <- Sv %>%
  left_join(bottom_intervals, by = c("Spatial_interval" = "trackline_interval")) %>% 
  mutate(depth_plot = ifelse(depth_mean >= 250, 250, depth_mean))

# Glimpse the data 
glimpse(Sv_and_depth)
```


```{r}
# Top panel
Sv_mean_plot <- ggplot(Sv_and_depth, aes(Distance_along, Sv_mean)) +
  geom_line() +
  labs(y=expression(mean~volume~backscatter~S[v]~(dB))) +
  theme(axis.title.x=element_blank())

# Bottom panel
bathymetry <- ggplot(Sv_and_depth, aes(Distance_along, depth_plot)) +
  geom_line(size = 0.5) +
  scale_y_reverse() +
  labs(x = "Distance along trackline (m)", y = "Depth (m)")

# Display the two panels in one figure
Sv_mean_plot / bathymetry
```
